### ISSUE TITLE
Update PostgreSQL JDBC Driver 

### ISSUE THREAD

**Issue by dclemenzi** [InCadence/coalesce#70]
This error is caused by this version of pgjdbc not including osgi.enterprise, which supposedly includes DataSourceFactory. https://github.com/pgjdbc/pgjdbc/issues/497

ERROR: Bundle org.postgresql.jdbc41 [222] Error starting mvn:org.postgresql/postgresql/9.4-1201-jdbc41 (org.osgi.framework.BundleException: Activator start error in bundle org.postgresql.jdbc41 [222].) java.lang.NoClassDefFoundError: org/osgi/service/jdbc/DataSourceFactory
                at org.postgresql.osgi.PGBundleActivator.start(PGBundleActivator.java:32)
                at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
                at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226)
                at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
                at org.apache.felix.framework.setActiveStartLevel(Felix.java:1371)
                at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
                at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundExcetion: org.osgi.service.jdbc.DataSourceFactory not found by postgresql.jdbc41 [222]
                at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
                at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                ... 7 more

**Comment by dclemenzi** [comment]
Since we are not dynamically loading the driver this does not directly affect our persister implementation.
